server:
  servlet:
    context-path: /
  port: 8090
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - image/png
    - image/jpeg
    - image/jpg
    - text/html
    - application/javascript
    - text/css
    - application/octet-stream
    - application/json
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.wyn.oauth.center.entity

#spring
spring:
  application:
    name: oauth-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.30:3306/oauth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#DataSource
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.20.30:3306/oauth?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
## 配置获取连接等待超时的时间
#    maxWait: 60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
## 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20

#log
logging:
  path: log

security:
  user:
    name: admin
    password: 123456
  oauth2:
    client:
      access-token-validity-seconds: 86400

management:
  security:
    enabled: true
    role: ADMIN
